project_id = "wipmmmlndhvsozrpepyt"

[functions.send-paypal-order-confirmation]
verify_jwt = false

[functions.validate-paypal-key]
verify_jwt = false

[functions.create-paypal-order]
verify_jwt = false

[functions.capture-paypal-order]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.validate-checkoutcom-key]
verify_jwt = false

[functions.create-checkoutcom-session]
verify_jwt = false

[functions.checkoutcom-webhook]
verify_jwt = false

[functions.send-checkoutcom-order-confirmation]
verify_jwt = false